[package]
name = "rmer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
dirs = "6.0.0"

[dependencies.uuid]
version = "1.18.1"
# Lets you generate random UUIDs
features = ["v4"]
